name: Reproduce

on:
  - push
  - workflow_dispatch

jobs:
  request:
    if: github.actor == 'chkimes'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
        
    - name: uname
      run: |
        uname -a
        
        echo "load snd-dummy"
        modprobe snd-dummy || true

        echo "installing linux-modules-extra"
        sudo apt-get install -y linux-modules-extra || true
        echo "load snd-dummy"
        modprobe snd-dummy || true

        echo "installing linux-modules-extra-azure"
        sudo apt-get install -y linux-modules-extra-azure || true
        echo "load snd-dummy"
        modprobe snd-dummy || true
